# Generated by Django 4.0.2 on 2022-04-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pigga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
