# Generated by Django 4.0.2 on 2022-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_pigga'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('dishname_id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dishname', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='website/imgs')),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
