# Generated by Django 4.0.2 on 2022-04-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_workingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='Time',
            field=models.CharField(max_length=30),
        ),
    ]
