# Generated by Django 4.0.2 on 2022-04-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_workingtime_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingtime',
            old_name='Days',
            new_name='DaysWT',
        ),
        migrations.RenameField(
            model_name='workingtime',
            old_name='Time',
            new_name='TimeWT',
        ),
    ]
