# Generated by Django 4.0.2 on 2022-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_days_workingtime_dayswt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('dishname_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=50)),
                ('dishname', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
