# Generated by Django 4.0.2 on 2022-04-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='desc',
            new_name='menudesc',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='dishname',
            new_name='menudishname',
        ),
    ]
