# Generated by Django 4.0.2 on 2022-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_desc_menu_menudesc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('Chefs_id', models.AutoField(primary_key=True, serialize=False)),
                ('Chefimage', models.ImageField(upload_to='images')),
                ('Chefname', models.CharField(max_length=50)),
                ('Chefdesc', models.CharField(max_length=500)),
            ],
        ),
    ]
