# Generated by Django 4.0.2 on 2022-04-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_testmonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmonials',
            name='Testmonialsimage',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
